name: bak9
version: git
summary: Rotational backup system for workstation users
description: |
  bak [OPTIONS] FILE [DIR] [COMMAND]

  Creates a backup .bak copy of FILE.

  If DIR is not specified, the copy is created in the same directory as FILE.

  If DIR is specified as -, or if the user lacks permissions to copy to DIR, the user's app data directory will be used instead.

  If multiple backups of FILE exist, the rotating filename extension used will be: .bak.N

  The most recent rotating backup will always be: .bak.0

  Pruning of rotating backups occurs after -n NUM copies.

  If the current backup is no different than its predecessor, copying will be skipped.

  Additional COMMANDs may be appended to list, compare, or delete backups.


base: core24
confinement: classic

platforms:
  amd64:
    build-on: amd64
    build-for: amd64
  arm64:
    build-on: [amd64, arm64]
    build-for: [arm64]
  armhf:
    build-on: [amd64, armhf]
    build-for: [armhf]

parts:
  bak:
    plugin: rust
    source: .
    build-attributes:
      - enable-patchelf

apps:
  bak:
    command: bin/bak
  bak9:
    command: bin/bak9
