[package]
name = "bak9"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0"
cron = "0"
hostname = "0"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
toml = "0"
validator = { version = "0", features = ["derive"] }
