[package]
name = "bak9"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0"
cron = "0.12.1"
hostname = "0.4.0"
serde = { version = "1.0.198", features = ["derive"] }
thiserror = "1.0.58"
toml = "0.8.12"
validator = { version = "0.18.1", features = ["derive"] }
